# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('rid', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('tid', models.IntegerField(blank=True, null=True)),
                ('language', models.TextField(blank=True, null=True)),
                ('time', models.TextField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('access', models.TextField(blank=True, null=True)),
                ('submittime', models.IntegerField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('output', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'submissions',
                'managed': True,
                'verbose_name_plural': 'submissions',
            },
        ),
    ]
