# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='code_upload',
            field=models.FileField(blank=True, upload_to=b''),
        ),
    ]
