# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_runs'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsCode',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('output', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subs_code',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Submit',
        ),
        migrations.AlterModelOptions(
            name='runs',
            options={'managed': False},
        ),
    ]
