# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_auto_20170108_1224'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='runs',
            table='runs',
        ),
    ]
