# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0005_auto_20170108_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('rid', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('output', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'submissions',
                'managed': False,
                'verbose_name_plural': 'submissions',
            },
        ),
        migrations.AlterModelOptions(
            name='runs',
            options={'managed': False, 'verbose_name_plural': 'runs'},
        ),
    ]
