# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='douban',
        ),
        migrations.RemoveField(
            model_name='account',
            name='homepage',
        ),
        migrations.RemoveField(
            model_name='account',
            name='weibo',
        ),
        migrations.RemoveField(
            model_name='account',
            name='weixin',
        ),
        migrations.AlterField(
            model_name='socialinfo',
            name='social',
            field=models.CharField(choices=[('fa-facebook', 'Facebook'), ('fa-github', 'Github'), ('fa-twitter', 'Twitter')], max_length=128),
        ),
    ]
