# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('pid', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('code', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('pro_type', models.TextField(blank=True, null=True)),
                ('contest', models.TextField()),
                ('status', models.TextField(blank=True, null=True)),
                ('pgroup', models.TextField(blank=True, null=True)),
                ('statement', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('imgext', models.TextField(blank=True, null=True)),
                ('pro_input', models.TextField(blank=True, null=True)),
                ('pro_output', models.TextField(blank=True, null=True)),
                ('timelimit', models.FloatField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('languages', models.TextField(blank=True, null=True)),
                ('options', models.TextField(blank=True, null=True)),
                ('displayio', models.IntegerField()),
                ('maxfilesize', models.IntegerField()),
                ('solved', models.IntegerField()),
                ('total', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'problems',
                'managed': True,
                'verbose_name_plural': 'problems',
            },
        ),
    ]
