# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contests',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('organiser', models.CharField(max_length=200)),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('announcment', models.TextField()),
            ],
            options={
                'db_table': 'contests',
                'managed': False,
            },
        ),
    ]
