# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_auto_20170128_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contests',
            options={'managed': True, 'verbose_name_plural': 'contests'},
        ),
    ]
