# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_auto_20170128_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contests',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
